"""empty message

Revision ID: 016cf1be551b
Revises: 461b97679ed1
Create Date: 2021-07-27 20:22:05.193791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016cf1be551b'
down_revision = '461b97679ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_branch_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ifsc', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('isBlocked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('token_users_tbl', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_users_tbl', 'email')
    op.drop_table('token_branch_tbl')
    # ### end Alembic commands ###
