"""empty message

Revision ID: 24265b6e2eaf
Revises: 36ffa81a2ac2
Create Date: 2021-08-28 12:40:27.383960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24265b6e2eaf'
down_revision = '36ffa81a2ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counter_tbl', sa.Column('sid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counter_tbl', 'sid')
    # ### end Alembic commands ###
