"""empty message

Revision ID: 29c6ad1a5b1e
Revises: a0b4810f027b
Create Date: 2021-08-31 20:32:36.180753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c6ad1a5b1e'
down_revision = 'a0b4810f027b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Time(), nullable=True),
    sa.Column('end', sa.Time(), nullable=True),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.Column('token', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('isBlocked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot_model')
    # ### end Alembic commands ###
