"""empty message

Revision ID: 36ffa81a2ac2
Revises: 016cf1be551b
Create Date: 2021-08-28 12:16:15.414280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ffa81a2ac2'
down_revision = '016cf1be551b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counter_tbl', sa.Column('sid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counter_tbl', 'sid')
    # ### end Alembic commands ###
