"""empty message

Revision ID: a0b4810f027b
Revises: 24265b6e2eaf
Create Date: 2021-08-31 20:24:28.917137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b4810f027b'
down_revision = '24265b6e2eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Time(), nullable=True),
    sa.Column('end', sa.Time(), nullable=True),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.Column('token', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('isBlocked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot_model')
    # ### end Alembic commands ###
